project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
lang: pt
website:
  title: "GECOMT"
  site-url: "https://gecomt.github.io/"
  favicon: "images/favicon.ico"
  twitter-card: true
  description: "Grupo de Estudos sobre Contabilidade e Mercado de Trabalho"
  google-analytics: "GTM-T9KC9QL7"
  back-to-top-navigation: true
  reader-mode: false
  navbar:
    type: light
    background: "#253e67"
    left:
      - href: blog/index.qmd
        text: Blog
      - href: https://gecomt.shinyapps.io/dashboard/
        text: Dashboard
        target: _blank
#      - href: artigos/index.qmd
#        text: Artigos
#      - href: palestras/index.qmd
#        text: Palestras
#      - href: Ensino/index.qmd
#        text: Ensino
#      - href: software/index.qmd
#        text: Software
      - text: Projetos
        menu:
          - text: contabiliDados
            href: https://contabilidados.com.br/
            target: _blank
          - text: Regulariza
            href: https://regulariza.shinyapps.io/dashboard/
            target: _blank
    right:
      - icon: github
        href: https://github.com/gecomt
      - icon: twitter-x
        href: https://twitter.com/gecomt_ufersa
      - icon: youtube
        href: https://www.youtube.com/@gecomt
      - icon: rss
        href: blog/index.xml
  page-footer:
    left: |
      
      [![](../images/ufersa.jpg){fig-alt="UFERSA" width=65px}](https://ufersa.edu.br)
    center: "© 2024 GECOMT licenciado sob CC BY-ND 4.0"
    right: |
      
      [![](../images/contabeis.png){fig-alt="contabeis" width=70px}](https://contabeis.ufersa.edu.br)
    #background: "#ffffff"

date-format: "D MMMM YYYY"

format:
  html:
    theme:
      light: united
      dark: cyborg
    css: styles.css
    toc: true
    html-math-method: katex
    include-in-header:
      file: header.html
mainfont: roboto
monofont: corrier new

blog:
  - folder: blog
    feed: true

comments:
  giscus:
    repo: gecomt/gecomt.github.io

